apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: ai-engine-workers
  namespace: default
  labels:
    app: ai-engine-workers
spec:
  replicas: 3
  strategy:
    blueGreen:
      # Blue-Green deployment for worker services
      activeService: ai-engine-workers-active
      previewService: ai-engine-workers-preview
      autoPromotionEnabled: false
      scaleDownDelaySeconds: 30
      prePromotionAnalysis:
        templates:
        - templateName: success-rate
        - templateName: workflow-failure-rate
        - templateName: cpu-usage
        - templateName: memory-usage
        args:
        - name: service-name
          value: ai-engine-workers-preview
      postPromotionAnalysis:
        templates:
        - templateName: success-rate
        - templateName: business-metrics
        args:
        - name: service-name
          value: ai-engine-workers-active
      previewReplicaCount: 1
      maxUnavailable: 0
      
  selector:
    matchLabels:
      app: ai-engine-workers
  template:
    metadata:
      labels:
        app: ai-engine-workers
    spec:
      serviceAccountName: ai-engine-workers
      containers:
      - name: worker
        image: ghcr.io/your-org/ai-engine-workers:latest
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: ai-engine-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: ai-engine-secrets
              key: redis-url
        - name: WORKER_TYPE
          value: "automation"
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 2000m
            memory: 2Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL

---
apiVersion: v1
kind: Service
metadata:
  name: ai-engine-workers-active
  labels:
    app: ai-engine-workers
spec:
  selector:
    app: ai-engine-workers
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http

---
apiVersion: v1
kind: Service
metadata:
  name: ai-engine-workers-preview
  labels:
    app: ai-engine-workers
spec:
  selector:
    app: ai-engine-workers
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http