global:
  scrape_interval: 15s     # Set the scrape interval to every 15 seconds
  evaluation_interval: 15s # Evaluate rules every 15 seconds
  scrape_timeout: 10s      # Timeout for scrape requests

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

# Rule files to load
rule_files:
  - "rules/alert_rules.yml"
  - "rules/recording_rules.yml"

# Scrape configurations
scrape_configs:
  # 1. Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # 2. API server metrics
  - job_name: 'api'
    metrics_path: '/metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['api:8000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '(.*)'
        replacement: '$1'

  # 3. Redis metrics via redis_exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis_exporter:9121']
    metrics_path: '/metrics'

  # 4. PostgreSQL metrics via postgres_exporter
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres_exporter:9187']
    metrics_path: '/metrics'

  # 5. Nginx metrics via nginx_exporter
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx_exporter:9113']
    metrics_path: '/metrics'

  # 6. Celery worker metrics via celery_exporter
  - job_name: 'celery'
    static_configs:
      - targets: ['celery_exporter:9540']
    metrics_path: '/metrics'

  # 7. System metrics via node_exporter
  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']
    metrics_path: '/metrics'

  # 8. Custom application metrics
  - job_name: 'custom_app_metrics'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['api:8000']

  # 9. Cadvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: '/metrics'

  # 10. Docker metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['docker_exporter:9323']
    metrics_path: '/metrics'
