"""
Workflow data-model
===================

This model supports **two representations** of a workflow:

1. Legacy **linear** representation – an ordered list of ``steps``.  
2. Modern **graph** representation – ``nodes`` and ``edges`` generated by the
   visual workflow editor.

The execution engine should prefer *nodes / edges* if present, otherwise fall
back to *steps* for backward-compatibility.

Additional sections:
• ``triggers``  – cron / event / manual trigger definitions.  
• ``approvals`` – human-in-the-loop approval requirements.  
• ``extra_metadata`` – free-form JSON for future extensions.
"""
from datetime import datetime
from typing import Optional, List, Dict
from sqlmodel import SQLModel, Field, JSON, Relationship

class Workflow(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    name: str
    description: Optional[str] = None
    status: str = "draft"  # draft, active, archived
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
    # Optional so programmatic tests / scripts can omit it.  In production this
    # should contain the username / service-account that created the workflow.
    created_by: Optional[str] = Field(default=None)

    # ------------------------------------------------------------------ #
    # Representations
    # ------------------------------------------------------------------ #

    # Legacy linear steps (kept for compatibility)
    # ------------------------------------------------------------------ #
    # Input-Process-Output (IPO) aware step definition
    # ------------------------------------------------------------------ #

    class StepIPO(SQLModel):
        """
        Explicit Input-Process-Output definition for a single workflow step.

        This nested model is *serialised as JSON* in the database to maintain
        backward-compatibility while providing clear semantics for each stage
        of a step.

        - ``input``    : description of required inputs (files, variables, etc.)
        - ``process`` : the action configuration (runner type, parameters, LLM prompt)
        - ``output``  : description / schema of the expected result
        - ``metadata``: free-form extras (confidence score, tags, etc.)
        """

        id: str
        name: str
        input: Dict = Field(default_factory=dict)
        process: Dict = Field(default_factory=dict)
        output: Dict = Field(default_factory=dict)
        metadata: Dict = Field(default_factory=dict)

    # Legacy linear steps now upgraded to explicit IPO structure but still
    # stored as JSON for seamless DB migration.
    steps: List[StepIPO] = Field(
        default_factory=list,
        sa_type=JSON,
        description="Ordered list of steps (Input-Process-Output aware).",
    )

    # Visual-editor graph representation
    nodes: List[Dict] = Field(
        default_factory=list,
        sa_type=JSON,
        description="Node definitions from the React Flow editor.",
    )
    edges: List[Dict] = Field(
        default_factory=list,
        sa_type=JSON,
        description="Edge definitions from the React Flow editor.",
    )
    triggers: List[Dict] = Field(default=[], sa_type=JSON)
    approvals: List[Dict] = Field(default=[], sa_type=JSON)
    extra_metadata: Dict = Field(default={}, sa_type=JSON) 